# Generated by Django 3.1 on 2020-08-14 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealStateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=32, null=True)),
                ('buy_currency', models.CharField(max_length=256, null=True)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=32, null=True)),
                ('rent_currency', models.CharField(max_length=256, null=True)),
                ('expenses_price', models.DecimalField(decimal_places=2, max_digits=32, null=True)),
                ('expenses_currency', models.CharField(max_length=256, null=True)),
                ('total_square_meters', models.DecimalField(decimal_places=2, max_digits=32, null=True)),
                ('covered_square_meters', models.DecimalField(decimal_places=2, max_digits=32, null=True)),
                ('number_of_rooms', models.SmallIntegerField(null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('town', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(default='argentina', max_length=256)),
                ('description', models.TextField(null=True)),
                ('raw_data', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
