# Generated by Django 3.1 on 2020-08-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_realstatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='realstatemodel',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
