# Generated by Django 3.1 on 2020-08-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_realstatemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realstatemodel',
            name='square_meters',
        ),
        migrations.AddField(
            model_name='realstatemodel',
            name='buy_currency',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='realstatemodel',
            name='country',
            field=models.CharField(default='argentina', max_length=256),
        ),
        migrations.AddField(
            model_name='realstatemodel',
            name='covered_square_meters',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='realstatemodel',
            name='expenses_currency',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='realstatemodel',
            name='number_of_rooms',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='realstatemodel',
            name='rent_currency',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='realstatemodel',
            name='total_square_meters',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='realstatemodel',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='realstatemodel',
            name='expenses_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='realstatemodel',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='realstatemodel',
            name='town',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
